name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 */12 * * *' 
  workflow_dispatch:    

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/GuilhermeAMendes/wisely-frontend.git
          git fetch upstream
          
      - name: Merge upstream changes
        run: |
          git checkout main    
          git merge upstream/main --allow-unrelated-histories -m "🔄 Sync with upstream" || (
            echo "Conflitos detectados, resolvendo automaticamente em favor do upstream..."
            git checkout --theirs .
            git add .
            git commit -m "🔄 Sync with upstream (conflitos resolvidos automaticamente)"
          )
          git push origin main
